import type {
  Source,
  ContentWithAnalysis,
  TrendingTopic,
  UntrackedSignal,
  PulseSummaryData,
  Prediction,
  Outlook,
} from '@/types';

export const mockSources: Source[] = [
  {
    id: 'src-001',
    name: 'Howard Marks',
    slug: 'howard-marks',
    bio: 'Co-chairman of Oaktree Capital Management. Known for his insightful memos on market cycles, risk assessment, and investor psychology.',
    avatar_url: '/avatars/howard-marks.jpg',
    domains: ['Macro / Liquidity'],
    scores: {
      intelligence: 4,
      intuition_eq: 5,
      sincerity: 4,
      access: 4,
      independence: 4,
      capital_at_risk: 5,
      reputational_sensitivity: 4,
      performance: 5,
    },
    weighted_score: 4.39,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-05T10:00:00Z',
  },
  {
    id: 'src-002',
    name: 'Michael Howell',
    slug: 'michael-howell',
    bio: 'CEO of CrossBorder Capital. Leading authority on global liquidity flows and their impact on asset prices.',
    avatar_url: '/avatars/michael-howell.jpg',
    domains: ['Macro / Liquidity'],
    scores: {
      intelligence: 4,
      intuition_eq: 4,
      sincerity: 5,
      access: 5,
      independence: 4,
      capital_at_risk: 2,
      reputational_sensitivity: 5,
      performance: 5,
    },
    weighted_score: 4.29,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-04T14:00:00Z',
  },
  {
    id: 'src-003',
    name: 'Mike Burry',
    slug: 'mike-burry',
    bio: 'Founder of Scion Asset Management. Famous for predicting the 2008 financial crisis. Contrarian investor with deep value focus.',
    avatar_url: '/avatars/mike-burry.jpg',
    domains: ['Macro / Liquidity'],
    scores: {
      intelligence: 5,
      intuition_eq: 3,
      sincerity: 5,
      access: 3,
      independence: 5,
      capital_at_risk: 5,
      reputational_sensitivity: 2,
      performance: 5,
    },
    weighted_score: 4.26,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-01T12:00:00Z',
  },
  {
    id: 'src-004',
    name: 'Ashok Varadhan',
    slug: 'ashok-varadhan',
    bio: 'Co-head of Goldman Sachs Global Banking & Markets. Deep expertise in rates, currencies, and macro trading.',
    avatar_url: '/avatars/ashok-varadhan.jpg',
    domains: ['Macro / Liquidity'],
    scores: {
      intelligence: 4,
      intuition_eq: 5,
      sincerity: 3,
      access: 5,
      independence: 4,
      capital_at_risk: 4,
      reputational_sensitivity: 4,
      performance: 4,
    },
    weighted_score: 4.10,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-01-30T08:00:00Z',
  },
  {
    id: 'src-005',
    name: 'Dylan Patel',
    slug: 'dylan-patel',
    bio: 'Chief analyst at SemiAnalysis. Leading voice on semiconductor supply chains, AI compute infrastructure, and chip architecture.',
    avatar_url: '/avatars/dylan-patel.jpg',
    domains: ['AI / Semiconductors'],
    scores: {
      intelligence: 4,
      intuition_eq: 4,
      sincerity: 4,
      access: 5,
      independence: 4,
      capital_at_risk: 2,
      reputational_sensitivity: 4,
      performance: 4,
    },
    weighted_score: 3.89,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-03T08:00:00Z',
  },
  {
    id: 'src-006',
    name: 'Brad Gerstner',
    slug: 'brad-gerstner',
    bio: 'Founder and CEO of Altimeter Capital. Technology and growth investor, frequent commentator on markets and macro.',
    avatar_url: '/avatars/brad-gerstner.jpg',
    domains: ['Macro / Liquidity', 'Venture / Startups'],
    scores: {
      intelligence: 4,
      intuition_eq: 4,
      sincerity: 4,
      access: 5,
      independence: 4,
      capital_at_risk: 5,
      reputational_sensitivity: 5,
      performance: 5,
    },
    weighted_score: 4.49,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },
  {
    id: 'src-007',
    name: 'Josh Wolfe',
    slug: 'josh-wolfe',
    bio: 'Co-founder and managing partner of Lux Capital. Invests in science and technology at the frontier—space, defense, climate, biology, and AI.',
    avatar_url: '/avatars/josh-wolfe.jpg',
    domains: ['Venture / Startups', 'AI / Semiconductors'],
    scores: {
      intelligence: 4,
      intuition_eq: 5,
      sincerity: 4,
      access: 4,
      independence: 5,
      capital_at_risk: 5,
      reputational_sensitivity: 4,
      performance: 4,
    },
    weighted_score: 4.37,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-12T00:00:00Z',
  },
  {
    id: 'src-008',
    name: 'Jeff Currie',
    slug: 'jeff-currie',
    bio: 'Head of Commodities at Carlyle. Former Global Head of Commodities Research at Goldman Sachs. Leading voice on oil, metals, and commodity markets.',
    avatar_url: '/avatars/jeff-currie.jpg',
    domains: ['Macro / Liquidity'],
    scores: {
      intelligence: 4,
      intuition_eq: 4,
      sincerity: 4,
      access: 5,
      independence: 5,
      capital_at_risk: 3,
      reputational_sensitivity: 4,
      performance: 4,
    },
    weighted_score: 4.15,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-12T00:00:00Z',
  },
  {
    id: 'src-009',
    name: 'Dan Sundheim',
    slug: 'dan-sundheim',
    bio: 'Founder and CIO of D1 Capital Partners. Former CIO of Viking Global Investors. Known for concentrated bets across public and private markets with exceptional long-term returns.',
    avatar_url: '/avatars/dan-sundheim.jpg',
    domains: ['Macro / Liquidity'],
    scores: {
      intelligence: 4,
      intuition_eq: 4,
      sincerity: 4,
      access: 4,
      independence: 4,
      capital_at_risk: 5,
      reputational_sensitivity: 4,
      performance: 4,
    },
    weighted_score: 4.12,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-25T00:00:00Z',
  },
];

export const mockContentWithAnalysis: ContentWithAnalysis[] = [
  {
    id: 'cnt-001',
    source_id: 'src-001',
    platform: 'substack',
    external_id: 'mock-001',
    title: 'The Illusion of Knowledge',
    url: 'https://example.com/howard-marks/illusion-of-knowledge',
    published_at: '2026-02-05T10:00:00Z',
    raw_text: '',
    created_at: '2026-02-05T10:00:00Z',
    source: mockSources[0],
    analysis: {
      id: 'ana-001',
      content_id: 'cnt-001',
      sentiment_overall: 'bearish',
      sentiment_score: -0.6,
      assets_mentioned: ['S&P 500', 'US Treasuries', 'Credit'],
      themes: ['Market Complacency', 'Risk Assessment', 'Cycle Positioning'],
      predictions: ['Market correction within 12 months'],
      key_quotes: [
        'When everyone agrees on the outlook, the outlook is usually wrong.',
        'The current market reminds me of 2007.',
      ],
      referenced_people: ['Warren Buffett', 'Charlie Munger'],
      summary:
        'Marks warns of excessive market complacency, drawing parallels to pre-2008 sentiment. Advocates for defensive positioning and heightened risk awareness.',
      created_at: '2026-02-05T10:00:00Z',
    },
  },
  {
    id: 'cnt-002',
    source_id: 'src-002',
    platform: 'youtube',
    external_id: 'mock-002',
    title: 'Global Liquidity Update: February 2026',
    url: 'https://youtube.com/watch?v=mock123',
    published_at: '2026-02-04T14:00:00Z',
    raw_text: '',
    created_at: '2026-02-04T14:00:00Z',
    source: mockSources[1],
    analysis: {
      id: 'ana-002',
      content_id: 'cnt-002',
      sentiment_overall: 'bearish',
      sentiment_score: -0.45,
      assets_mentioned: ['Bitcoin', 'NASDAQ', 'Gold', 'US Dollar'],
      themes: ['Liquidity Tightening', 'Fed Balance Sheet', 'Private Credit'],
      predictions: ['Risk assets face headwinds in Q1 2026', '$500B liquidity drain over next quarter'],
      key_quotes: [
        'Global liquidity is entering a critical inflection point.',
        'The Global Liquidity Index leads risk assets by about 6 weeks.',
      ],
      referenced_people: ['Jay Powell', 'Stanley Druckenmiller'],
      summary:
        'Howell identifies a net liquidity drain despite private credit offsetting Fed tightening. Signals caution for risk assets over the next quarter.',
      created_at: '2026-02-04T14:00:00Z',
    },
  },
  {
    id: 'cnt-003',
    source_id: 'src-005',
    platform: 'substack',
    external_id: 'mock-003',
    title: 'GPU CapEx: The Coming Correction',
    url: 'https://semianalysis.com/gpu-capex-correction',
    published_at: '2026-02-03T08:00:00Z',
    raw_text: '',
    created_at: '2026-02-03T08:00:00Z',
    source: mockSources[4],
    analysis: {
      id: 'ana-003',
      content_id: 'cnt-003',
      sentiment_overall: 'bearish',
      sentiment_score: -0.35,
      assets_mentioned: ['NVIDIA', 'Microsoft', 'AMD', 'TSMC'],
      themes: ['GPU CapEx Saturation', 'AI Infrastructure', 'Semiconductor Cycle'],
      predictions: ['15-20% reduction in GPU orders H2 2026', 'NVIDIA guidance revision likely'],
      key_quotes: [
        "The question isn't whether this spending slows — it's when and how abruptly.",
        'Our supply chain checks suggest a 15-20% reduction in orders.',
      ],
      referenced_people: ['Jensen Huang', 'Satya Nadella', 'Lisa Su'],
      summary:
        'Patel presents supply chain evidence of upcoming GPU CapEx reduction. Argues hyperscaler spending has overshot near-term AI revenue potential.',
      created_at: '2026-02-03T08:00:00Z',
    },
  },
  {
    id: 'cnt-004',
    source_id: 'src-003',
    platform: 'twitter',
    external_id: 'mock-004',
    title: 'Burry 13F Filing Analysis — Q4 2025',
    url: 'https://example.com/burry-13f-q4-2025',
    published_at: '2026-02-01T12:00:00Z',
    raw_text: '',
    created_at: '2026-02-01T12:00:00Z',
    source: mockSources[2],
    analysis: {
      id: 'ana-004',
      content_id: 'cnt-004',
      sentiment_overall: 'bearish',
      sentiment_score: -0.7,
      assets_mentioned: ['QQQ', 'Gold', 'GLD', 'NASDAQ'],
      themes: ['Tech Correction', 'Hard Assets', 'Portfolio Positioning'],
      predictions: ['Tech-led market correction imminent', 'Gold outperforms in H1 2026'],
      key_quotes: [
        'Massive increase in put positions on QQQ.',
        'Portfolio concentration suggests high conviction.',
      ],
      referenced_people: ['Michael Burry'],
      summary:
        "Burry's 13F shows aggressive bearish positioning on tech via QQQ puts, paired with gold longs. High conviction contrarian bet on tech correction.",
      created_at: '2026-02-01T12:00:00Z',
    },
  },
];

export const mockTrendingTopics: TrendingTopic[] = [
  { rank: 1, title: 'GPU CapEx Saturation', mentions: 8, trend: 'up' },
  { rank: 2, title: 'Sovereign Debt Concerns', mentions: 6, trend: 'up' },
  { rank: 3, title: 'Liquidity Tightening', mentions: 5, trend: 'stable' },
  { rank: 4, title: 'Market Complacency', mentions: 4, trend: 'up' },
  { rank: 5, title: 'Private Credit Bubble', mentions: 4, trend: 'up' },
  { rank: 6, title: 'Gold as Safe Haven', mentions: 3, trend: 'stable' },
  { rank: 7, title: 'AI Revenue Gap', mentions: 3, trend: 'down' },
  { rank: 8, title: 'Fed Balance Sheet', mentions: 2, trend: 'stable' },
];

export const mockUntrackedSignals: UntrackedSignal[] = [
  {
    name: 'Stanley Druckenmiller',
    mentioned_by: ['Michael Howell'],
    context: 'Referenced in liquidity analysis as having similar positioning concerns',
  },
  {
    name: 'Jensen Huang',
    mentioned_by: ['Dylan Patel'],
    context: 'NVIDIA CEO — GPU CapEx narrative depends on his forward guidance',
  },
  {
    name: 'Warren Buffett',
    mentioned_by: ['Howard Marks'],
    context: 'Cash pile positioning cited as signal of market overvaluation',
  },
  {
    name: 'Lisa Su',
    mentioned_by: ['Dylan Patel'],
    context: 'AMD strategy relevant to semiconductor cycle thesis',
  },
];

export const mockPulseSummary: PulseSummaryData = {
  sentiment: 'Cautiously Bearish',
  theme: 'Risk asset headwinds from liquidity tightening and overextended tech valuations',
  divergences:
    'Marks focuses on cycle psychology while Howell emphasizes mechanical liquidity flows. Patel isolated on semis-specific thesis. Burry most aggressively positioned.',
  signal_count: '12 new items from 5 sources',
};

export const mockPredictions: Prediction[] = [
  {
    id: 'pred-001',
    content_id: 'cnt-001',
    source_id: 'src-001',
    claim: 'Market correction within 12 months',
    themes: ['Market Complacency', 'Cycle Positioning'],
    assets_mentioned: ['S&P 500'],
    sentiment: 'bearish',
    time_horizon: '12 months',
    confidence: 'medium',
    specificity: 'directional',
    date_made: '2026-02-05T10:00:00Z',
    notes: '',
    created_at: '2026-02-05T10:00:00Z',
  },
  {
    id: 'pred-002',
    content_id: 'cnt-002',
    source_id: 'src-002',
    claim: 'Risk assets face headwinds in Q1 2026',
    themes: ['Liquidity Tightening'],
    assets_mentioned: ['NASDAQ'],
    sentiment: 'bearish',
    time_horizon: '3 months',
    confidence: 'high',
    specificity: 'thematic',
    date_made: '2026-02-04T14:00:00Z',
    notes: '',
    created_at: '2026-02-04T14:00:00Z',
  },
  {
    id: 'pred-003',
    content_id: 'cnt-002',
    source_id: 'src-002',
    claim: '$500B liquidity drain over next quarter',
    themes: ['Liquidity Tightening', 'Fed Balance Sheet'],
    assets_mentioned: [],
    sentiment: 'bearish',
    time_horizon: '3 months',
    confidence: 'high',
    specificity: 'hard',
    date_made: '2026-02-04T14:00:00Z',
    notes: '',
    created_at: '2026-02-04T14:00:00Z',
  },
  {
    id: 'pred-004',
    content_id: 'cnt-003',
    source_id: 'src-005',
    claim: '15-20% reduction in GPU orders H2 2026',
    themes: ['GPU CapEx Saturation', 'Semiconductor Cycle'],
    assets_mentioned: ['NVIDIA'],
    sentiment: 'bearish',
    time_horizon: '6 months',
    confidence: 'medium',
    specificity: 'hard',
    date_made: '2026-02-03T08:00:00Z',
    notes: '',
    created_at: '2026-02-03T08:00:00Z',
  },
  {
    id: 'pred-005',
    content_id: 'cnt-003',
    source_id: 'src-005',
    claim: 'NVIDIA guidance revision likely',
    themes: ['GPU CapEx Saturation'],
    assets_mentioned: ['NVIDIA'],
    sentiment: 'bearish',
    time_horizon: '6 months',
    confidence: 'medium',
    specificity: 'directional',
    date_made: '2026-02-03T08:00:00Z',
    notes: '',
    created_at: '2026-02-03T08:00:00Z',
  },
  {
    id: 'pred-006',
    content_id: 'cnt-004',
    source_id: 'src-003',
    claim: 'Tech-led market correction imminent',
    themes: ['Tech Correction'],
    assets_mentioned: ['QQQ'],
    sentiment: 'bearish',
    time_horizon: '3 months',
    confidence: 'high',
    specificity: 'directional',
    date_made: '2026-02-01T12:00:00Z',
    notes: '',
    created_at: '2026-02-01T12:00:00Z',
  },
  {
    id: 'pred-007',
    content_id: 'cnt-004',
    source_id: 'src-003',
    claim: 'Gold outperforms in H1 2026',
    themes: ['Hard Assets'],
    assets_mentioned: ['Gold'],
    sentiment: 'bullish',
    time_horizon: '6 months',
    confidence: 'high',
    specificity: 'directional',
    date_made: '2026-02-01T12:00:00Z',
    notes: '',
    created_at: '2026-02-01T12:00:00Z',
  },
];

export const mockOutlook: Outlook[] = [
  {
    id: 'outlook-short',
    time_horizon: 'short',
    domain: 'general',
    title: 'The Liquidity Air Pocket',
    subtitle: 'Next 30 days',
    thesis_intro: 'The immediate environment is defined by tightening financial conditions and elevated risk across crypto and geopolitical spheres.',
    thesis_points: [
      { heading: 'Liquidity Crunch', content: 'Global liquidity is falling. Federal Reserve liquidity projected to drop ~10% over the next nine months. Repo market spreads are widening - early stress signals.' },
      { heading: 'Crypto as Smoke Alarm', content: 'Bitcoin has broken down technically against both gold and the dollar. Acting as a leading indicator for broader risk assets. Quantum computing fears have triggered selling by long-term holders.' },
      { heading: 'Geopolitical Flashpoints', content: "Aggressive moves to secure physical resources. The 'Greenland Gambit' signals intent to control rare earth supply chains critical for AI and defense." },
      { heading: 'AI Security Vulnerabilities', content: 'Rapid open-source AI agent adoption has exposed major security gaps. Enterprise-grade alternatives with proper guardrails expected within 3 months.' },
    ],
    positioning: [
      'Short duration fixed income - avoid long-term bonds, hold T-bills as dry powder',
      'Trim high-beta tech and crypto exposure',
      'Maintain tactical cash position',
    ],
    key_themes: ['liquidity crunch', 'crypto breakdown', 'geopolitical risk', 'AI security'],
    sentiment: 'bearish',
    confidence: 72,
    supporting_sources: [
      { name: 'Michael Howell', weight: 30 },
      { name: 'Howard Marks', weight: 25 },
      { name: 'Mike Burry', weight: 25 },
      { name: 'Dylan Patel', weight: 20 },
    ],
    last_updated: '2026-02-06T10:00:00Z',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'outlook-medium',
    time_horizon: 'medium',
    domain: 'general',
    title: 'The Physical Pivot',
    subtitle: 'Next 12 months',
    thesis_intro: 'A K-shaped economy emerges. AI drives growth while the broader market confronts physical constraints and rising real capital costs.',
    thesis_points: [
      { heading: 'Gold to $5,000', content: 'Targeting $4,900-5,000/oz by end of 2026. Driven by central bank accumulation and retail adoption of the debasement narrative.' },
      { heading: 'Tale of Two Halves', content: 'H1 2026: Asset prices struggle under liquidity withdrawal and rising real rates. H2 2026: Potential nominal boom if yield curve control is implemented to fund re-industrialization.' },
      { heading: 'From Chips to Grid', content: 'The AI constraint shifts from silicon to electricity. Data center power demand is the new bottleneck. Industrial commodities (copper, uranium) and energy infrastructure become the trades.' },
      { heading: 'Memory Squeeze', content: 'Server memory costs expected to double by late 2026. AI demand is crowding out all other use cases. Structural shift in semiconductor economics.' },
    ],
    positioning: [
      'Gold ~15% allocation as core anchor',
      'Long infrastructure (PAVE), short semiconductors (SOXX)',
      'Overweight: nuclear, gas turbines (GE Vernova), grid components',
      'Overweight: memory manufacturers (Micron, Western Digital)',
      'Underweight: high-multiple tech',
    ],
    key_themes: ['gold', 'yield curve control', 'energy bottleneck', 'semiconductors', 'K-shaped economy'],
    sentiment: 'cautious',
    confidence: 65,
    supporting_sources: [
      { name: 'Michael Howell', weight: 30 },
      { name: 'Dylan Patel', weight: 25 },
      { name: 'Howard Marks', weight: 25 },
      { name: 'Mike Burry', weight: 20 },
    ],
    last_updated: '2026-02-06T10:00:00Z',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'outlook-long',
    time_horizon: 'long',
    domain: 'general',
    title: 'The Sovereignty Trade',
    subtitle: '5+ year horizon',
    thesis_intro: 'A new structural regime defined by Capital Wars. The race for physical control over the means of intelligence production.',
    thesis_points: [
      { heading: 'Monetary Reset', content: 'US debt trajectory: 250% of GDP by mid-2050s. If real debt value is maintained in gold terms, implies $10,000/oz by mid-2030s, $25,000/oz by 2050s.' },
      { heading: 'Resource Nationalism', content: 'Rules-based order gives way to physical possession as law. Nations stockpile critical minerals. Permanent premium on resource sovereignty. US faces binary choice: sacrifice dollar or lose AI race.' },
      { heading: 'Power Consumption Explosion', content: 'US data center capacity: 33 GW (2024) \u2192 176 GW (2035). Fivefold increase. Massive nuclear and natural gas buildout required.' },
      { heading: 'Social Bifurcation', content: 'AI is labor-saving at scale. Four out of five jobs potentially threatened. Social polarization increases. UBI becomes policy necessity.' },
    ],
    positioning: [
      'Gold as long-term anchor - potential for significant repricing',
      'Strategic commodities: copper, uranium, rare earths',
      'Energy infrastructure: nuclear, natural gas',
      'Avoid: long-duration sovereign debt',
      'High conviction, concentrated positions over broad diversification',
    ],
    key_themes: ['monetary reset', 'resource nationalism', 'energy infrastructure', 'AI labor displacement', 'gold repricing'],
    sentiment: 'cautious',
    confidence: 58,
    supporting_sources: [
      { name: 'Michael Howell', weight: 35 },
      { name: 'Howard Marks', weight: 30 },
      { name: 'Mike Burry', weight: 20 },
      { name: 'Dylan Patel', weight: 15 },
    ],
    last_updated: '2026-02-06T10:00:00Z',
    created_at: '2026-02-01T00:00:00Z',
  },
];
