import type {
  Source,
  ContentWithAnalysis,
  TrendingTopic,
  UntrackedSignal,
  PulseSummaryData,
  Prediction,
} from '@/types';

export const mockSources: Source[] = [
  {
    id: 'src-001',
    name: 'Howard Marks',
    slug: 'howard-marks',
    bio: 'Co-chairman of Oaktree Capital Management. Known for his insightful memos on market cycles, risk assessment, and investor psychology.',
    avatar_url: '/avatars/howard-marks.jpg',
    domains: ['Macro / Liquidity'],
    scores: {
      intelligence: 4,
      intuition_eq: 5,
      sincerity: 4,
      access: 4,
      independence: 4,
      capital_at_risk: 5,
      reputational_sensitivity: 4,
      performance: 5,
    },
    weighted_score: 4.39,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-05T10:00:00Z',
  },
  {
    id: 'src-002',
    name: 'Michael Howell',
    slug: 'michael-howell',
    bio: 'CEO of CrossBorder Capital. Leading authority on global liquidity flows and their impact on asset prices.',
    avatar_url: '/avatars/michael-howell.jpg',
    domains: ['Macro / Liquidity'],
    scores: {
      intelligence: 4,
      intuition_eq: 4,
      sincerity: 5,
      access: 5,
      independence: 4,
      capital_at_risk: 2,
      reputational_sensitivity: 5,
      performance: 5,
    },
    weighted_score: 4.29,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-04T14:00:00Z',
  },
  {
    id: 'src-003',
    name: 'Mike Burry',
    slug: 'mike-burry',
    bio: 'Founder of Scion Asset Management. Famous for predicting the 2008 financial crisis. Contrarian investor with deep value focus.',
    avatar_url: '/avatars/mike-burry.jpg',
    domains: ['Macro / Liquidity'],
    scores: {
      intelligence: 5,
      intuition_eq: 3,
      sincerity: 5,
      access: 3,
      independence: 5,
      capital_at_risk: 5,
      reputational_sensitivity: 2,
      performance: 5,
    },
    weighted_score: 4.26,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-01T12:00:00Z',
  },
  {
    id: 'src-004',
    name: 'Ashok Varadhan',
    slug: 'ashok-varadhan',
    bio: 'Co-head of Goldman Sachs Global Banking & Markets. Deep expertise in rates, currencies, and macro trading.',
    avatar_url: '/avatars/ashok-varadhan.jpg',
    domains: ['Macro / Liquidity'],
    scores: {
      intelligence: 4,
      intuition_eq: 5,
      sincerity: 3,
      access: 5,
      independence: 4,
      capital_at_risk: 4,
      reputational_sensitivity: 4,
      performance: 4,
    },
    weighted_score: 4.10,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-01-30T08:00:00Z',
  },
  {
    id: 'src-005',
    name: 'Dylan Patel',
    slug: 'dylan-patel',
    bio: 'Chief analyst at SemiAnalysis. Leading voice on semiconductor supply chains, AI compute infrastructure, and chip architecture.',
    avatar_url: '/avatars/dylan-patel.jpg',
    domains: ['AI / Semiconductors'],
    scores: {
      intelligence: 4,
      intuition_eq: 4,
      sincerity: 4,
      access: 5,
      independence: 4,
      capital_at_risk: 2,
      reputational_sensitivity: 4,
      performance: 4,
    },
    weighted_score: 3.89,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-03T08:00:00Z',
  },
];

export const mockContentWithAnalysis: ContentWithAnalysis[] = [
  {
    id: 'cnt-001',
    source_id: 'src-001',
    platform: 'substack',
    external_id: 'mock-001',
    title: 'The Illusion of Knowledge',
    url: 'https://example.com/howard-marks/illusion-of-knowledge',
    published_at: '2026-02-05T10:00:00Z',
    raw_text: '',
    created_at: '2026-02-05T10:00:00Z',
    source: mockSources[0],
    analysis: {
      id: 'ana-001',
      content_id: 'cnt-001',
      sentiment_overall: 'bearish',
      sentiment_score: -0.6,
      assets_mentioned: ['S&P 500', 'US Treasuries', 'Credit'],
      themes: ['Market Complacency', 'Risk Assessment', 'Cycle Positioning'],
      predictions: ['Market correction within 12 months'],
      key_quotes: [
        'When everyone agrees on the outlook, the outlook is usually wrong.',
        'The current market reminds me of 2007.',
      ],
      referenced_people: ['Warren Buffett', 'Charlie Munger'],
      summary:
        'Marks warns of excessive market complacency, drawing parallels to pre-2008 sentiment. Advocates for defensive positioning and heightened risk awareness.',
      created_at: '2026-02-05T10:00:00Z',
    },
  },
  {
    id: 'cnt-002',
    source_id: 'src-002',
    platform: 'youtube',
    external_id: 'mock-002',
    title: 'Global Liquidity Update: February 2026',
    url: 'https://youtube.com/watch?v=mock123',
    published_at: '2026-02-04T14:00:00Z',
    raw_text: '',
    created_at: '2026-02-04T14:00:00Z',
    source: mockSources[1],
    analysis: {
      id: 'ana-002',
      content_id: 'cnt-002',
      sentiment_overall: 'bearish',
      sentiment_score: -0.45,
      assets_mentioned: ['Bitcoin', 'NASDAQ', 'Gold', 'US Dollar'],
      themes: ['Liquidity Tightening', 'Fed Balance Sheet', 'Private Credit'],
      predictions: ['Risk assets face headwinds in Q1 2026', '$500B liquidity drain over next quarter'],
      key_quotes: [
        'Global liquidity is entering a critical inflection point.',
        'The Global Liquidity Index leads risk assets by about 6 weeks.',
      ],
      referenced_people: ['Jay Powell', 'Stanley Druckenmiller'],
      summary:
        'Howell identifies a net liquidity drain despite private credit offsetting Fed tightening. Signals caution for risk assets over the next quarter.',
      created_at: '2026-02-04T14:00:00Z',
    },
  },
  {
    id: 'cnt-003',
    source_id: 'src-005',
    platform: 'substack',
    external_id: 'mock-003',
    title: 'GPU CapEx: The Coming Correction',
    url: 'https://semianalysis.com/gpu-capex-correction',
    published_at: '2026-02-03T08:00:00Z',
    raw_text: '',
    created_at: '2026-02-03T08:00:00Z',
    source: mockSources[4],
    analysis: {
      id: 'ana-003',
      content_id: 'cnt-003',
      sentiment_overall: 'bearish',
      sentiment_score: -0.35,
      assets_mentioned: ['NVIDIA', 'Microsoft', 'AMD', 'TSMC'],
      themes: ['GPU CapEx Saturation', 'AI Infrastructure', 'Semiconductor Cycle'],
      predictions: ['15-20% reduction in GPU orders H2 2026', 'NVIDIA guidance revision likely'],
      key_quotes: [
        "The question isn't whether this spending slows — it's when and how abruptly.",
        'Our supply chain checks suggest a 15-20% reduction in orders.',
      ],
      referenced_people: ['Jensen Huang', 'Satya Nadella', 'Lisa Su'],
      summary:
        'Patel presents supply chain evidence of upcoming GPU CapEx reduction. Argues hyperscaler spending has overshot near-term AI revenue potential.',
      created_at: '2026-02-03T08:00:00Z',
    },
  },
  {
    id: 'cnt-004',
    source_id: 'src-003',
    platform: 'twitter',
    external_id: 'mock-004',
    title: 'Burry 13F Filing Analysis — Q4 2025',
    url: 'https://example.com/burry-13f-q4-2025',
    published_at: '2026-02-01T12:00:00Z',
    raw_text: '',
    created_at: '2026-02-01T12:00:00Z',
    source: mockSources[2],
    analysis: {
      id: 'ana-004',
      content_id: 'cnt-004',
      sentiment_overall: 'bearish',
      sentiment_score: -0.7,
      assets_mentioned: ['QQQ', 'Gold', 'GLD', 'NASDAQ'],
      themes: ['Tech Correction', 'Hard Assets', 'Portfolio Positioning'],
      predictions: ['Tech-led market correction imminent', 'Gold outperforms in H1 2026'],
      key_quotes: [
        'Massive increase in put positions on QQQ.',
        'Portfolio concentration suggests high conviction.',
      ],
      referenced_people: ['Michael Burry'],
      summary:
        "Burry's 13F shows aggressive bearish positioning on tech via QQQ puts, paired with gold longs. High conviction contrarian bet on tech correction.",
      created_at: '2026-02-01T12:00:00Z',
    },
  },
];

export const mockTrendingTopics: TrendingTopic[] = [
  { rank: 1, title: 'GPU CapEx Saturation', mentions: 8, trend: 'up' },
  { rank: 2, title: 'Sovereign Debt Concerns', mentions: 6, trend: 'up' },
  { rank: 3, title: 'Liquidity Tightening', mentions: 5, trend: 'stable' },
  { rank: 4, title: 'Market Complacency', mentions: 4, trend: 'up' },
  { rank: 5, title: 'Private Credit Bubble', mentions: 4, trend: 'up' },
  { rank: 6, title: 'Gold as Safe Haven', mentions: 3, trend: 'stable' },
  { rank: 7, title: 'AI Revenue Gap', mentions: 3, trend: 'down' },
  { rank: 8, title: 'Fed Balance Sheet', mentions: 2, trend: 'stable' },
];

export const mockUntrackedSignals: UntrackedSignal[] = [
  {
    name: 'Stanley Druckenmiller',
    mentioned_by: ['Michael Howell'],
    context: 'Referenced in liquidity analysis as having similar positioning concerns',
  },
  {
    name: 'Jensen Huang',
    mentioned_by: ['Dylan Patel'],
    context: 'NVIDIA CEO — GPU CapEx narrative depends on his forward guidance',
  },
  {
    name: 'Warren Buffett',
    mentioned_by: ['Howard Marks'],
    context: 'Cash pile positioning cited as signal of market overvaluation',
  },
  {
    name: 'Lisa Su',
    mentioned_by: ['Dylan Patel'],
    context: 'AMD strategy relevant to semiconductor cycle thesis',
  },
];

export const mockPulseSummary: PulseSummaryData = {
  sentiment: 'Cautiously Bearish',
  theme: 'Risk asset headwinds from liquidity tightening and overextended tech valuations',
  divergences:
    'Marks focuses on cycle psychology while Howell emphasizes mechanical liquidity flows. Patel isolated on semis-specific thesis. Burry most aggressively positioned.',
  signal_count: '12 new items from 5 sources',
};

export const mockPredictions: Prediction[] = [
  {
    id: 'pred-001',
    content_id: 'cnt-001',
    source_id: 'src-001',
    claim: 'Market correction within 12 months',
    asset_or_theme: 'S&P 500',
    direction: 'down',
    time_horizon: '12 months',
    confidence: 'medium',
    status: 'pending',
    resolved_at: null,
    notes: '',
    created_at: '2026-02-05T10:00:00Z',
  },
  {
    id: 'pred-002',
    content_id: 'cnt-002',
    source_id: 'src-002',
    claim: 'Risk assets face headwinds in Q1 2026',
    asset_or_theme: 'NASDAQ',
    direction: 'down',
    time_horizon: '3 months',
    confidence: 'high',
    status: 'pending',
    resolved_at: null,
    notes: '',
    created_at: '2026-02-04T14:00:00Z',
  },
  {
    id: 'pred-003',
    content_id: 'cnt-002',
    source_id: 'src-002',
    claim: '$500B liquidity drain over next quarter',
    asset_or_theme: 'Global Liquidity',
    direction: 'down',
    time_horizon: '3 months',
    confidence: 'high',
    status: 'pending',
    resolved_at: null,
    notes: '',
    created_at: '2026-02-04T14:00:00Z',
  },
  {
    id: 'pred-004',
    content_id: 'cnt-003',
    source_id: 'src-005',
    claim: '15-20% reduction in GPU orders H2 2026',
    asset_or_theme: 'NVIDIA',
    direction: 'down',
    time_horizon: '6 months',
    confidence: 'medium',
    status: 'pending',
    resolved_at: null,
    notes: '',
    created_at: '2026-02-03T08:00:00Z',
  },
  {
    id: 'pred-005',
    content_id: 'cnt-003',
    source_id: 'src-005',
    claim: 'NVIDIA guidance revision likely',
    asset_or_theme: 'NVIDIA',
    direction: 'down',
    time_horizon: '6 months',
    confidence: 'medium',
    status: 'pending',
    resolved_at: null,
    notes: '',
    created_at: '2026-02-03T08:00:00Z',
  },
  {
    id: 'pred-006',
    content_id: 'cnt-004',
    source_id: 'src-003',
    claim: 'Tech-led market correction imminent',
    asset_or_theme: 'QQQ',
    direction: 'down',
    time_horizon: '3 months',
    confidence: 'high',
    status: 'pending',
    resolved_at: null,
    notes: '',
    created_at: '2026-02-01T12:00:00Z',
  },
  {
    id: 'pred-007',
    content_id: 'cnt-004',
    source_id: 'src-003',
    claim: 'Gold outperforms in H1 2026',
    asset_or_theme: 'Gold',
    direction: 'up',
    time_horizon: '6 months',
    confidence: 'high',
    status: 'pending',
    resolved_at: null,
    notes: '',
    created_at: '2026-02-01T12:00:00Z',
  },
];
